### ISSUE TITLE
Regenerating maps throws an error 

### ISSUE THREAD

**Issue by ilovecats516** [timberline-secondary/hackerspace#235]
Here's the error:

`AttributeError at /maps/1/regenerate/
'NoneType' object has no attribute 'get_absolute_url'`

**Comment by tylerecouture** [comment]
Can you add more context?  It looks like it can't be regenerated because it doesn't exist yet.  You might still need to create the first map?  That shoudl already exist.  Did you go through the rest of the setup from the bash setup script?  Maybe you didn't `loaddata` to import an initial set of data for the site?

**Comment by ilovecats516** [comment]
The map exists, the default quests were there. I added my own quests and deleted the default quests, and they went to regenerate the map.

**Comment by tylerecouture** [comment]
Hmm.. Ok.  Each map has a starting object. If you deleted that object, that might be the problem here.  Instead of regenerating, try editing the map to give it a new starting object.  Then regenerate.

**Comment by ilovecats516** [comment]
Yep, that fixed it. The `initial object id` was set to 0, so I changed it to a quest id that exists. Thanks.
