### ISSUE TITLE
Available quests incorrect

### ISSUE THREAD

**Issue by mizzgoldberg** [timberline-secondary/hackerspace#450]
When logged in as a student, this is what appears as available:
![availablequests](https://user-images.githubusercontent.com/55294487/79603603-85bbf880-80a1-11ea-8aea-16435fbb9ced.png)

When I click on one of those quests, it is not actually available:
![notreally](https://user-images.githubusercontent.com/55294487/79603625-8f456080-80a1-11ea-902d-9a7098bd747e.png)

And the quests that SHOULD be available are not. I should have access to orientation quests based on what I've completed.
![completed](https://user-images.githubusercontent.com/55294487/79603860-f105ca80-80a1-11ea-9b0e-0b99ed0bbe24.png)

**Comment by mizzgoldberg** [comment]
Currently all quests are appearing as available on techhub.
![allavailable](https://user-images.githubusercontent.com/55294487/79604724-79d13600-80a3-11ea-88a3-9a7eb762d44a.png)

**Comment by tylerecouture** [comment]
Fixed with 11f241bd07d6cbfdc10c87198425e4958249a524

To manually recalculate all users' available quests, go to the django admin: 
- Prereq all conditions mets In Prequisites section
- Tick one of the item 9doesn't matter which ones or how many, but you have to select at least one)
- At the bottom in the drop down menu, choose: "Recalculate...blah blah"

It will do it in the background and might take some time, depending on how big the deck is (Hackerspace might take 30 minutes or more, others will only take less than a minute)
